services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ea-invitation-api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_DATABASE=ea_invitation
      - DB_USERNAME=ea_user
      - DB_PASSWORD=ea_password
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
    networks:
      - ea-network

  mysql:
    image: mysql:8.0
    container_name: ea-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ea_invitation
      MYSQL_USER: ea_user
      MYSQL_PASSWORD: ea_password
      MYSQL_ROOT_PASSWORD: ea_root_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ea-network

  redis:
    image: redis:7-alpine
    container_name: ea-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - ea-network

volumes:
  mysql_data:
  redis_data:

networks:
  ea-network:
    driver: bridge