# docker-compose.yml
version: '3.8'

services:
  ea-invitation-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ea-invitation-api
    restart: unless-stopped
    volumes:
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    environment:
      - RUN_SEEDERS=false
    networks:
      - ea-network

  nginx:
    image: nginx:alpine
    container_name: ea-invitation-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ea-invitation-api
    networks:
      - ea-network

  mysql:
    image: mysql:8.0
    container_name: ea-invitation-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ea_invitation
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: password
      MYSQL_USER: ea_user
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ea-network

volumes:
  mysql_data:

networks:
  ea-network:
    driver: bridge