version: '3.8'

services:
  # Laravel API Service
  ea-invitation-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ea-invitation-api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend/ea-invitation-api:/var/www/html
      - ./logs/laravel:/var/www/html/storage/logs
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      - mysql
      - redis
    networks:
      - ea-invitation-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: ea-invitation-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - ea-invitation-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: ea-invitation-redis
    restart: unless-stopped
    volumes:
      - ./redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - ea-invitation-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: ea-invitation-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
      - /var/www/ea-invitation/backend/ea-invitation-api/public:/var/www/html/public
    depends_on:
      - ea-invitation-api
    networks:
      - ea-invitation-network

networks:
  ea-invitation-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: