# /var/www/ea-invitation-api/docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ea-invitation-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
    networks:
      - app-network
    environment:
      - APP_ENV=production
      - APP_DEBUG=true
    env_file:
      - .env.production

  nginx:
    image: nginx:alpine
    container_name: ea-invitation-api-nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: ea-invitation-api-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ea_invitation_api
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_USER: ea_user
      MYSQL_PASSWORD: your_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: ea-invitation-api-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: