version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ea-invitation-app
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./vendor:/var/www/vendor
    depends_on:
      - db

  nginx:
    image: nginx:stable
    container_name: ea-invitation-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: ea-invitation-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  certbot:
    image: certbot/certbot
    container_name: ea-invitation-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt

volumes:
  db_data:
