version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eainvitation-api
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - APP_NAME=EAInvitationAPI
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://eainvitaiton.com
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - MIDTRANS_SERVER_KEY=${MIDTRANS_SERVER_KEY}
      - MIDTRANS_CLIENT_KEY=${MIDTRANS_CLIENT_KEY}
      - MIDTRANS_IS_PRODUCTION=false
      - MIDTRANS_MERCHANT_ID=${MIDTRANS_MERCHANT_ID}
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./storage:/var/www/html/storage
      - ./public:/var/www/html/public
      - ./docker/ssl:/etc/nginx/ssl
    depends_on:
      - db
      - redis
    networks:
      - eainvitation-network

  db:
    image: mysql:8.0
    container_name: eainvitation-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - eainvitation-network

  redis:
    image: redis:7-alpine
    container_name: eainvitation-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - eainvitation-network

volumes:
  mysql_data:

networks:
  eainvitation-network:
    driver: bridge