version: '3.8'

services:
  app:
    build: .
    container_name: ea-invitation-api
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ea-invitation-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ea_invitation
      MYSQL_USER: ea_user
      MYSQL_PASSWORD: ea_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  nginx:
    image: nginx:stable
    container_name: ea-invitation-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - app
    networks:
      - laravel

  certbot:
    image: certbot/certbot
    container_name: ea-invitation-certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt

volumes:
  db_data:
  certbot-etc:
  certbot-var:

networks:
  laravel:
