version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    image: ea-invitation-api:latest
    container_name: ea-invitation-api
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - APP_NAME=EA-Invitation-API
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=false
      - APP_URL=https://api.eainvitaiton.com
      - LOG_CHANNEL=stack
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=error
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      - MIDTRANS_SERVER_KEY=${MIDTRANS_SERVER_KEY}
      - MIDTRANS_CLIENT_KEY=${MIDTRANS_CLIENT_KEY}
      - MIDTRANS_IS_PRODUCTION=false
      - MIDTRANS_MERCHANT_ID=${MIDTRANS_MERCHANT_ID}
      - RUN_SEEDERS=${RUN_SEEDERS:-false}
    depends_on:
      - db
    networks:
      - ea-invitation-network

  db:
    image: mysql:8.0
    container_name: ea-invitation-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - ea-invitation-network

networks:
  ea-invitation-network:
    driver: bridge

volumes:
  db_data:
    driver: local