# ea-invitation-api/.github/workflows/deploy.yml
name: Deploy Laravel API to VPS

on:
  push:
    branches: [ main, production ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql
        coverage: xdebug
        
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Generate key
      run: php artisan key:generate
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
        
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/production'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd /var/www/ea-invitation-api
          
          # Pull latest code
          git pull origin main
          
          # Copy environment file
          cp .env.production .env
          
          # Build and restart containers
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
          
          # Wait for containers to be ready
          sleep 30
          
          # Run Laravel commands inside container
          docker-compose exec -T ea-invitation-api php artisan migrate --force
          docker-compose exec -T ea-invitation-api php artisan config:clear
          docker-compose exec -T ea-invitation-api php artisan cache:clear
          docker-compose exec -T ea-invitation-api php artisan route:clear
          docker-compose exec -T ea-invitation-api php artisan view:clear
          docker-compose exec -T ea-invitation-api php artisan config:cache
          docker-compose exec -T ea-invitation-api php artisan route:cache
          docker-compose exec -T ea-invitation-api php artisan view:cache
          
          # Cleanup old images
          docker system prune -f