name: Deploy Backend API

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

    - name: Add VPS to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to VPS
      run: |
        ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          # Navigate to project directory
          cd /var/www/ea-invitation

          # Pull latest changes
          git pull origin main

          # Copy environment file
          cp backend/.env.production backend/ea-invitation-api/.env

          # Build and restart backend container
          docker-compose down ea-invitation-api
          docker-compose build ea-invitation-api --no-cache
          docker-compose up -d ea-invitation-api

          # Wait for container to be ready
          sleep 30

          # Run Laravel commands inside container
          docker-compose exec -T ea-invitation-api php artisan migrate --force
          docker-compose exec -T ea-invitation-api php artisan config:cache
          docker-compose exec -T ea-invitation-api php artisan route:cache
          docker-compose exec -T ea-invitation-api php artisan view:cache
          docker-compose exec -T ea-invitation-api php artisan storage:link

          # Restart nginx to reload configuration
          docker-compose restart nginx

          echo "Backend deployment completed successfully!"
        EOF

    - name: Health Check
      run: |
        sleep 60
        curl -f https://api.eainvitaiton.com/health || exit 1

    - name: Notify deployment status
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Backend deployment successful!"
        else
          echo "❌ Backend deployment failed!"
        fi